# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=http://localhost
@port=5000


//List all Products
GET {{host}}:{{port}}/api/CaseStudy

###

//Get specific Product by id
@productToGetId = 1
GET {{host}}:{{port}}/api/CaseStudy/{{productToGetId}}

###

//Add new Product
POST {{host}}:{{port}}/api/CaseStudy
Content-Type: application/json

{
    "name": "Camp Kinetic",
    "url": "https://www.alza.cz/sport/camp-kinetic-d12937061.htm",
    "price": 1589,
    "description": "Tlumič pádu - pro osoby s hmotností od 40 do 120 kg",
    "quantity": 7
}

###

//Update existing Product by id
@productToUpdateId = 1

PUT {{host}}:{{port}}/api/CaseStudy/{{productToUpdateId}}
Content-Type: application/json

{
    "name": "Camp Kinetic",
    "url": "https://www.alza.cz/sport/camp-kinetic-d12937061.htm",
    "price": 1589,
    "description": "Tlumič pádu - pro osoby s hmotností od 40 do 120 kg",
    "quantity": 7
}

###

//Delete exisiting ToDoItem by id
@productToDeleteId = 1
DELETE {{host}}:{{port}}/api/CaseStudy/{{productToDeleteId}}
